#!/bin/sh

IP1=`curl ifconfig.co --interface pppoe-wan`
#echo $IP1

. /lib/functions/network.sh
#network_find_wan NET_IF
network_get_ipaddr NET_ADDR wan
#echo "${NET_ADDR}"

if [ $IP1 != ${NET_ADDR} ]
then
        echo Reconnecting wan - grey IP detected: $IP1 - ${NET_ADDR}
        ifup wan
else
        echo Yeah! White IP detected: ${NET_ADDR}
fi
