#!/bin/sh

if [[ "$ACTION" != "ifup" || "$INTERFACE" != "wan" ]]
then
        exit
fi

. /lib/functions/network.sh; network_get_ipaddr ip wan
ip2=`curl ifconfig.co --interface pppoe-wan`

if [ $ip != $ip2 ]
then
        logger -t grey_ip "Reconnecting wan - grey IP detected: $ip"
        ifup wan
else
        logger -t grey_ip "Yeah! White IP detected: $ip"
fi
