#!/bin/sh

IP4=`curl -4 ifconfig.co --interface pppoe-wan`
IP6=`curl ifconfig.co --interface pppoe-wan`
#echo $IP4

. /lib/functions/network.sh
#network_find_wan NET_IF
network_get_ipaddr NET_ADDR wan
#echo "${NET_ADDR}"

if [ $IP4 != ${NET_ADDR} ]
then
        echo Reconnecting wan - grey IP detected: $IP4 - ${NET_ADDR}
        ifup wan
else
        echo Yeah! White IP detected: ${NET_ADDR}
        curl -4 -k https://ydns.io/hosts/update/_token_ 
        echo -e "\n"
        curl -k "https://www.duckdns.org/update?domains=_domens_&ip=$IP4&ipv6=$IP6&token=_token_
fi
